<?php
require_once "inc/config.php"; require_once "inc/admin_auth.php"; require_admin_permission($pdo,'dashboard');
$cards=[
['Müştərilər',(int)$pdo->query("SELECT COUNT(*) FROM customers"),'customers.php'],
['Vendorlar',(int)$pdo->query("SELECT COUNT(*) FROM customers WHERE type='partner'"),'customers.php?type=partner'],
['Moderasiya',(int)$pdo->query("SELECT COUNT(*) FROM listings WHERE status='moderation'"),'listings.php?status=moderation'],
['Tender gözləyən',(int)$pdo->query("SELECT COUNT(*) FROM tenders WHERE status='pending'"),'tenders.php?status=pending'],
['Açıq şikayətlər',(int)$pdo->query("SELECT COUNT(*) FROM listing_complaints WHERE status IN ('new','reviewed')"),'complaints.php'],
['Aktiv abunəlik',(int)$pdo->query("SELECT COUNT(*) FROM customer_subs WHERE status='active'"),'subscriptions.php?status=active'],
['Ödəniş xətası',(int)$pdo->query("SELECT COUNT(*) FROM payments WHERE status='failed'"),'payments.php?status=failed'],
['Gəlir',(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM payments WHERE status='paid'"),'payments.php?status=paid'],
];
?>
<!doctype html><html lang="az"><head><?php include "inc/head.php"; ?></head><body><div class="app-main"><div id="app-wrapper" class="app-wrapper d-flex flex-column align-items-stretch min-vh-100"><?php include "inc/sidebar.php"; ?><?php include "inc/navbar.php"; ?><div class="app-content-wrapper py-13"><div class="container-fluid"><div class="page-header pb-7"><h2 class="fw-semibold fs-7">EndOut İdarəetmə Paneli</h2><div class="text-muted">Real vaxt DB göstəriciləri və Action Required növbəsi</div></div><div class="row g-4"><?php foreach($cards as $i=>$c):?><div class="col-xl-3 col-md-6"><a href="<?=$c[2]?>" class="text-decoration-none"><div class="pure-card card-bg shadow-custom rounded-custom h-100"><div class="pure-card-body"><div class="text-muted"><?=$c[0]?></div><div class="fs-7 fw-bold"><?=is_float($c[1])?number_format($c[1],2).' AZN':$c[1]?></div></div></div></a></div><?php endforeach;?></div><div class="row g-4 mt-2"><div class="col-xl-7"><div class="pure-card card-bg shadow-custom rounded-custom"><div class="pure-card-header"><h3 class="pure-card-title m-0">Action Required</h3></div><div class="pure-card-body"><ul class="list-group list-group-flush"><li class="list-group-item d-flex justify-content-between">Moderasiya gözləyən elanlar <a href="listings.php?status=moderation">Bax</a></li><li class="list-group-item d-flex justify-content-between">Pending tenderlər <a href="tenders.php?status=pending">Bax</a></li><li class="list-group-item d-flex justify-content-between">Yeni/araşdırılan şikayətlər <a href="complaints.php">Bax</a></li><li class="list-group-item d-flex justify-content-between">Uğursuz ödənişlər <a href="payments.php?status=failed">Bax</a></li></ul></div></div></div><div class="col-xl-5"><div class="pure-card card-bg shadow-custom rounded-custom"><div class="pure-card-header"><h3 class="pure-card-title m-0">Təhlükəsizlik</h3></div><div class="pure-card-body"><p>Admin dəyişiklikləri audit log-a yazılır.</p><p>Ödəniş statusu admin paneldən manual dəyişdirilmir.</p><a href="audit-logs.php" class="btn btn-outline-primary">Audit log</a></div></div></div></div></div></div><?php include "inc/footer.php"; ?></div></div><?php include "inc/scripts_url.php"; ?></body></html>
