<?php
require_once "inc/config.php"; require_once "inc/admin_auth.php"; require_admin_permission($pdo,'moderation');
$status=(string)($_GET['status']??'');$q=trim((string)($_GET['q']??''));$where=[];$p=[];
if(in_array($status,['draft','moderation','active','rejected','expired'],true)){ $where[]='l.status=?';$p[]=$status; }
if($q!==''){ $where[]='(l.title LIKE ? OR CAST(l.id AS CHAR)=? OR c.full_name LIKE ?)';$like="%$q%";array_push($p,$like,$q,$like); }
$sql="SELECT l.id,l.title,l.status,l.price,l.currency,l.created_at,c.full_name vendor_name,m.name market_name FROM listings l JOIN customers c ON c.id=l.customer_id LEFT JOIN markets m ON m.id=l.market_id";
if($where)$sql.=" WHERE ".implode(' AND ',$where);$sql.=" ORDER BY l.id DESC LIMIT 100";
$stmt=$pdo->prepare($sql);$stmt->execute($p);$rows=$stmt->fetchAll(PDO::FETCH_ASSOC);$csrf=admin_csrf_token();
?>
<!doctype html><html lang="az"><head><?php include "inc/head.php"; ?></head><body><div class="app-main"><div id="app-wrapper" class="app-wrapper d-flex flex-column align-items-stretch min-vh-100"><?php include "inc/sidebar.php"; ?><?php include "inc/navbar.php"; ?><div class="app-content-wrapper py-13"><div class="container-fluid"><div class="page-header pb-7"><h2 class="fw-semibold fs-7">Elan moderasiyası</h2></div><form class="row g-3 mb-5"><div class="col-md-6"><input class="form-control" name="q" value="<?=admin_h($q)?>" placeholder="Başlıq, vendor və ya ID"></div><div class="col-md-4"><select class="form-control" name="status"><option value="">Bütün statuslar</option><?php foreach(['moderation','active','rejected','draft','expired'] as $s):?><option <?=$status===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filtr</button></div></form><div class="pure-card card-bg shadow-custom rounded-custom"><div class="pure-card-body table-responsive"><table class="table align-middle"><tr><th>ID</th><th>Elan</th><th>Vendor</th><th>Market</th><th>Status</th><th>Əməliyyat</th></tr><?php foreach($rows as $r):?><tr><td>#<?=$r['id']?></td><td><?=admin_h($r['title'])?><br><small><?=admin_h($r['price'].' '.$r['currency'])?></small></td><td><?=admin_h($r['vendor_name'])?></td><td><?=admin_h($r['market_name']??'-')?></td><td><?=admin_h($r['status'])?></td><td><form method="post" action="api/management/listing_moderation.php" class="d-flex gap-2"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status" class="form-control form-control-sm"><option value="active">Təsdiq</option><option value="moderation">Yenidən baxış</option><option value="rejected">Rədd</option></select><input name="reason" class="form-control form-control-sm" placeholder="Səbəb (rədd üçün)"><button class="btn btn-sm btn-primary">Tətbiq</button></form></td></tr><?php endforeach;?></table></div></div></div></div><?php include "inc/footer.php"; ?></div></div><?php include "inc/scripts_url.php"; ?></body></html>
